name: xaquacrop-dev
channels:
  - conda-forge
dependencies:
  - python=3.9

  # Testing
  - pytest

  # code checks
  - black=21.5b2
  - cpplint
  - flake8=3.9.2
  - flake8-bugbear=21.3.2  # used by flake8, find likely bugs
  - flake8-comprehensions=3.1.0  # used by flake8, linting of unnecessary comprehensions
  - isort>=5.2.1  # check that imports are in the right order
  - mypy=0.910
  - pre-commit>=2.9.2
  - pycodestyle  # used by flake8
  - pyupgrade

  # Dask
  - dask

  - pip
  - pip:
    - git+https://github.com/Joeperdefloep/xarray-simlab/@docs
